### ISSUE TITLE
Your implementation can be inserted in a existent fragment?

### ISSUE THREAD

**Issue by LukeDaniel16** [kai-morich/SimpleBluetoothLeTerminal#10]
Hi, i need usage communication with BLE (with Arduino) and your app was a unique app that works with my CC2541, i'm read your code and i have a fragment screen (from NavigationDrawer) and i need implements a big part of your code here, everything works until we click on some device to connect, this error is returned to me: 

`
2020-01-03 16:54:41.755 25872-25872/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.agrolucros2019, PID: 25872
    java.lang.IllegalArgumentException: No view found for id 0x7f09009c (com.example.agrolucros2019:id/fragment) for fragment TerminalFragment{25fdc20 (8f432817-1c28-4b66-a395-1f86dbd4b273) id=0x7f09009c terminal}
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:875)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
        at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7097)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
`

Do you have a some idea that can be cause it?

I'm really desesperate now, thanks in advance!

Works since here: 
[This image](https://imgur.com/FGMJhSM)

When i pressed on a device, error return.

**Comment by kai-morich** [comment]
your question looks more related to NavigationDrawer usage than to my code, so I doubt that I can help here
